# Generated by Django 6.0 on 2026-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("cover_image", models.ImageField(blank=True, upload_to="books/")),
                (
                    "amazon_link",
                    models.URLField(blank=True, verbose_name="Amazon Purchase Link"),
                ),
                (
                    "goodreads_link",
                    models.URLField(blank=True, verbose_name="Goodreads Link"),
                ),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("publication_year", models.IntegerField()),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this book on the homepage"
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_year"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="GatewayPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About Arun"),
                            ("books", "Books"),
                            ("themes", "Themes Overview"),
                            ("media", "Media & Press"),
                            ("contact", "Contact"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Main content (can use basic HTML)"
                    ),
                ),
                (
                    "sidebar_content",
                    models.TextField(blank=True, help_text="Optional sidebar content"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["page_type"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to this theme in the existing reading room",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order in navigation"),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
