# Generated by Django 6.0 on 2026-01-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about how they found the newsletter",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter/X"),
                            ("goodreads", "Goodreads"),
                            ("amazon", "Amazon Author"),
                            ("newsletter", "Newsletter"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("website", "Website"),
                        ],
                        max_length=50,
                    ),
                ),
                ("profile_url", models.URLField()),
                ("display_text", models.CharField(blank=True, max_length=100)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon name (e.g., 'linkedin', 'envelope')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=True, help_text="Show in website footer"
                    ),
                ),
                (
                    "show_in_sidebar",
                    models.BooleanField(
                        default=False, help_text="Show in website sidebar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Profile",
                "verbose_name_plural": "Social Media Profiles",
                "ordering": ["order", "platform"],
            },
        ),
        migrations.AlterField(
            model_name="gatewaypage",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About Arun"),
                    ("books", "Books"),
                    ("themes", "Themes Overview"),
                    ("media", "Media & Press"),
                    ("contact", "Contact"),
                    ("connect", "Connect"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
