# Generated by Django 6.0 on 2026-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0002_newslettersubscriber_socialmediaprofile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={"ordering": ["bucket", "order", "name"]},
        ),
        migrations.AddField(
            model_name="theme",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("system", "The System"),
                    ("me_us", "Me/Us"),
                    ("future_india", "Future of India"),
                ],
                default="system",
                help_text="Which of Arun's three buckets this theme belongs to",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="amazon_link",
            field=models.URLField(
                blank=True,
                verbose_name="https://www.amazon.com/s/ref=dp_byline_sr_book_1?ie=UTF8&field-author=Arun+Maira&text=Arun+Maira&sort=relevancerank&search-alias=books",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="goodreads_link",
            field=models.URLField(
                blank=True,
                verbose_name="https://www.goodreads.com/author/show/1493903.Arun_Maira",
            ),
        ),
    ]
