# Generated by Django 6.0 on 2026-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0003_alter_theme_options_theme_bucket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version (auto-generated)",
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Main article content (can use basic HTML)"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, help_text="Short summary (optional)"),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True, help_text="Link if published elsewhere"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF or document file (optional)",
                        upload_to="articles/documents/%Y/%m/",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image for the article",
                        upload_to="articles/images/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publish_date",
                    models.DateField(
                        blank=True,
                        help_text="When to publish (leave blank for immediate)",
                        null=True,
                    ),
                ),
                (
                    "reading_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated reading time in minutes",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(default="Arun Maira", max_length=200)),
                (
                    "site_tagline",
                    models.CharField(
                        blank=True,
                        default="A quiet space for thoughtful inquiry",
                        max_length=300,
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(default="admin@arunmaira.com", max_length=254),
                ),
                (
                    "contact_email",
                    models.EmailField(default="contact@arunmaira.com", max_length=254),
                ),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                (
                    "enable_comments",
                    models.BooleanField(
                        default=False, help_text="Enable comments on articles"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, help_text="Put site in maintenance mode"
                    ),
                ),
                (
                    "default_theme_bucket_order",
                    models.CharField(
                        default="system,me_us,future_india",
                        help_text="Order of theme buckets (comma-separated)",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio Recording"),
                            ("video", "Video Recording"),
                            ("interview", "Interview"),
                            ("lecture", "Lecture"),
                            ("conversation", "Conversation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        help_text="Audio/Video file (max 500MB)",
                        upload_to="talks/media/%Y/%m/",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True, help_text="YouTube, Vimeo, or other external link"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image",
                        upload_to="talks/thumbnails/%Y/%m/",
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=200)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="HH:MM:SS format", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Feature this talk on the listening page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talk",
                "verbose_name_plural": "Talks",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Show this file to website visitors"
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["-publication_year"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="gatewaypage",
            options={
                "ordering": ["navigation_order", "page_type"],
                "verbose_name": "Gateway Page",
                "verbose_name_plural": "Gateway Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
            },
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={
                "ordering": ["bucket", "order", "name"],
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("speaking", "Speaking Engagement"),
                    ("media", "Media Inquiry"),
                    ("academic", "Academic/Research"),
                    ("editorial", "Editorial Inquiry"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about this inquiry"
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="response_sent",
            field=models.BooleanField(
                default=False, help_text="Response has been sent"
            ),
        ),
        migrations.AddField(
            model_name="gatewaypage",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for this page",
                upload_to="pages/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="gatewaypage",
            name="navigation_order",
            field=models.IntegerField(
                default=0, help_text="Order in navigation (lower numbers first)"
            ),
        ),
        migrations.AddField(
            model_name="gatewaypage",
            name="show_in_navigation",
            field=models.BooleanField(
                default=True, help_text="Show this page in main navigation"
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, help_text="Email address has been confirmed"
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Last newsletter sent to this subscriber",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("general", "General Updates"),
                    ("articles", "New Articles Only"),
                    ("events", "Events & Talks Only"),
                    ("full", "All Updates"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="socialmediaprofile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Brief description of how Arun uses this platform"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="amazon_link",
            field=models.URLField(blank=True, verbose_name="Amazon Link"),
        ),
        migrations.AlterField(
            model_name="book",
            name="goodreads_link",
            field=models.URLField(blank=True, verbose_name="Goodreads Link"),
        ),
        migrations.AlterField(
            model_name="gatewaypage",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About Arun"),
                    ("books", "Books"),
                    ("themes", "Themes Overview"),
                    ("media", "Media & Press"),
                    ("contact", "Contact"),
                    ("connect", "Connect"),
                    ("reading", "Reading Ideas"),
                    ("listening", "Listening to Ideas"),
                    ("articles", "Articles"),
                    ("talks", "Talks & Recordings"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediaprofile",
            name="platform",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("twitter", "Twitter/X"),
                    ("goodreads", "Goodreads"),
                    ("amazon", "Amazon Author"),
                    ("newsletter", "Newsletter"),
                    ("youtube", "YouTube"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("website", "Website"),
                    ("podcast", "Podcast"),
                    ("medium", "Medium"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["is_read", "submitted_at"],
                name="gateway_con_is_read_8d0265_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["category"], name="gateway_con_categor_44cf10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(
                fields=["email", "is_active"], name="gateway_new_email_2bf1cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(
                fields=["is_active", "subscription_type"],
                name="gateway_new_is_acti_1e2702_idx",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="themes",
            field=models.ManyToManyField(
                blank=True, help_text="Select relevant themes", to="gateway.theme"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="themes",
            field=models.ManyToManyField(blank=True, to="gateway.theme"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "publish_date"], name="gateway_art_status_8e9d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="gateway_art_slug_1e9a4f_idx"),
        ),
    ]
