# Generated by Django 6.0 on 2026-01-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0004_article_sitesettings_talk_uploadedfile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_status",
            field=models.BooleanField(
                default=True,
                help_text="Overall site status (different from maintenance mode)",
                verbose_name="Site Status",
            ),
        ),
    ]
