# Generated by Django 6.0 on 2026-01-19 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0005_sitesettings_site_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={
                "ordering": ["-subscribed_at"],
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Article author",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("system", "The System"),
                    ("me_us", "Me/Us"),
                    ("india", "Future of India"),
                ],
                default="system",
                help_text="Main category matching reading.html",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="estimated_read_time",
            field=models.CharField(
                blank=True, help_text="Auto-calculated: '5 min read'", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="featured_article",
            field=models.BooleanField(
                default=False, help_text="Feature this article (shows star in admin)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.TextField(
                blank=True, help_text="SEO description (max 160 characters)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_keywords",
            field=models.CharField(
                blank=True, help_text="SEO keywords (comma-separated)", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="subtopic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complex-systems", "Complex Systems: Social Change"),
                    ("democracy-policy", "Democracy and Public Policy"),
                    ("evolution-economics", "Evolution of Economics"),
                    ("jobs-employment", "Jobs and Employment"),
                    ("business-ethics", "Business Ethics"),
                    ("purpose-lives", "Purpose of Our Lives"),
                    ("listening-others", "Listening to Others"),
                    ("future-india", "Future of India"),
                ],
                help_text="Specific subtopic from reading.html",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Short summary for cards in reading.html"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When to publish"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="reading_time",
            field=models.IntegerField(
                blank=True,
                help_text="Estimated reading time in minutes (auto-calculated)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "subtopic"], name="gateway_art_categor_06d151_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["featured_article"], name="gateway_art_feature_0f8f43_idx"
            ),
        ),
    ]
