# Generated by Django 6.0 on 2026-04-13 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0006_alter_newslettersubscriber_options_article_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="gateway_art_status_8e9d6c_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="gateway_art_slug_1e9a4f_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="gateway_art_categor_06d151_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="gateway_art_feature_0f8f43_idx",
        ),
        migrations.AddField(
            model_name="article",
            name="video_id",
            field=models.CharField(
                blank=True,
                help_text="YouTube Video ID (e.g., GomzK5HohO4)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("system", "The System"),
                    ("me_us", "Me/Us"),
                    ("india", "Future of India"),
                    ("READ", "Read (Articles)"),
                    ("LISTEN", "Listen (Videos/Talks)"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="document",
            field=models.FileField(blank=True, upload_to="articles/documents/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="estimated_read_time",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(blank=True, help_text="Short summary for cards"),
        ),
        migrations.AlterField(
            model_name="article",
            name="external_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_article",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(blank=True, upload_to="articles/images/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="reading_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="subtopic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complex-systems", "Complex Systems: Social Change"),
                    ("democracy-policy", "Democracy and Public Policy"),
                    ("evolution-economics", "Evolution of Economics"),
                    ("jobs-employment", "Jobs and Employment"),
                    ("business-ethics", "Business Ethics"),
                    ("purpose-lives", "Purpose of Our Lives"),
                    ("listening-others", "Listening to Others"),
                    ("future-india", "Future of India"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="themes",
            field=models.ManyToManyField(blank=True, to="gateway.theme"),
        ),
        migrations.RemoveField(
            model_name="article",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="article",
            name="meta_keywords",
        ),
    ]
