# Generated by Django 6.0 on 2026-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0007_remove_article_gateway_art_status_8e9d6c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("system", "The System"),
                    ("me_us", "Me/Us"),
                    ("india", "Future of India"),
                    ("READ", "Read (Articles)"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
