# Generated by Django 6.0 on 2026-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0008_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
