# Generated by Django 6.0 on 2026-04-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0009_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="video_id",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="talk",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talk",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="talk",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="talks/thumbnails/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
