# Generated by Django 6.0 on 2026-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0010_talk_video_id_alter_talk_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={"ordering": ["bucket", "order", "name"]},
        ),
        migrations.RemoveField(
            model_name="theme",
            name="external_link",
        ),
        migrations.AddField(
            model_name="book",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="gateway.theme"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("system", "The System"),
                    ("me_us", "Me/Us"),
                    ("future_india", "Future of India"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="theme",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
