# Generated by Django 6.0 on 2026-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0011_alter_theme_options_remove_theme_external_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatewaypage",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About Arun"),
                    ("books", "Books"),
                    ("themes", "Themes Overview"),
                    ("media", "Media & Press"),
                    ("contact", "Contact"),
                    ("reading", "Reading Ideas"),
                    ("listening", "Listening to Ideas"),
                    ("articles", "Articles"),
                    ("talks", "Talks & Recordings"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediaprofile",
            name="platform",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("twitter", "Twitter/X"),
                    ("goodreads", "Goodreads"),
                    ("amazon", "Amazon Author"),
                    ("newsletter", "Newsletter"),
                ],
                max_length=50,
            ),
        ),
    ]
