# Generated by Django 6.0 on 2026-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0012_alter_gatewaypage_page_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
