# Generated by Django 6.0 on 2026-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0013_alter_article_publish_date_alter_article_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=600),
        ),
    ]
