# Generated by Django 6.0 on 2026-05-05 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0014_alter_article_slug_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
