# Generated by Django 5.1.15 on 2026-05-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0015_alter_article_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='video_id',
        ),
    ]
